import type { UnitType } from "./IUnitTypes.ts"

export const unitTypes: UnitType[] = [
  {
    id: "2x2-basic",
    name: "2x2 Unit Series (4x4 ft)",
    description: "Our most basic property in compact package. Perfect for small storage needs.",
    price: 99,
    imageUrl: "assets/images/unit-types/2x2-basic.png",
    dimensions: {
      width: 4,
      length: 4,
      height: 8,
    },
    features: ["24/7 Access", "Climate Controlled", "Ground Level"],
    availability: "available",
    popularSize: true,
    totalUnits: 50,
    occupiedUnits: 35,
  },
  {
    id: "5x5-standard",
    name: "5x5 Storage Unit",
    description: "Medium-sized storage perfect for apartment contents or business inventory.",
    price: 149,
    imageUrl: "assets/images/unit-types/5x5-standard.png",
    dimensions: {
      width: 5,
      length: 5,
      height: 8,
    },
    features: ["24/7 Access", "Climate Controlled", "Drive-Up Access", "Security Cameras"],
    availability: "limited",
    totalUnits: 40,
    occupiedUnits: 38,
  },
  {
    id: "10x10-premium",
    name: "10x10 Premium Storage",
    description: "Large storage solution ideal for household items or commercial use.",
    price: 299,
    imageUrl: "assets/images/unit-types/10x10-premium.png",
    dimensions: {
      width: 10,
      length: 10,
      height: 10,
    },
    features: ["24/7 Access", "Climate Controlled", "Drive-Up Access", "Security Cameras", "Extended Height"],
    availability: "waitlist",
    totalUnits: 30,
    occupiedUnits: 30,
  },
  {
    id: "7x10-business",
    name: "7x10 Business Unit",
    description: "Designed for business storage with extra security features.",
    price: 249,
    imageUrl: "assets/images/unit-types/7x10-business.png",
    dimensions: {
      width: 7,
      length: 10,
      height: 8,
    },
    features: [
      "24/7 Access",
      "Climate Controlled",
      "Business Center Access",
      "Enhanced Security",
      "Inventory Management",
    ],
    availability: "available",
    totalUnits: 25,
    occupiedUnits: 15,
  },
  {
    id: "15x20-warehouse",
    name: "15x20 Warehouse Space",
    description: "Commercial-grade storage solution with premium amenities.",
    price: 599,
    imageUrl: "assets/images/unit-types/15x20-warehouse.png",
    dimensions: {
      width: 15,
      length: 20,
      height: 12,
    },
    features: [
      "24/7 Access",
      "Climate Controlled",
      "Loading Dock Access",
      "Forklift Available",
      "Commercial Grade Security",
    ],
    availability: "limited",
    popularSize: true,
    totalUnits: 15,
    occupiedUnits: 13,
  },
]

