import type { Unit } from "./IUnit"

export const units: Unit[] = [
  {
    id: "2",
    status: "Rented",
    unitType: "Storage Unit (10 x 8)",
    customer: "Jane K. Walker",
    phone: "",
    cellPhone: "(903) 372-9022",
    email: "jkwohome7@gmail.com",
    balance: "$0.00",
  },
  {
    id: "3",
    status: "Available",
    unitType: "Storage Unit (10 x 8)",
    customer: "",
    phone: "",
    cellPhone: "",
    email: "",
    balance: "$0.00",
  },
  {
    id: "2",
    status: "Rented",
    unitType: "Storage Unit (10 x 8)",
    customer: "Jane K. Walker",
    phone: "",
    cellPhone: "(903) 372-9022",
    email: "jkwohome7@gmail.com",
    balance: "$0.00",
  },
  {
    id: "3",
    status: "Available",
    unitType: "Storage Unit (10 x 8)",
    customer: "",
    phone: "",
    cellPhone: "",
    email: "",
    balance: "$0.00",
  },
  {
    id: "4",
    status: "Late",
    unitType: "Storage Unit (10 x 8)",
    customer: "Robert Smith",
    phone: "(903) 555-0123",
    cellPhone: "(903) 555-0124",
    email: "rsmith@email.com",
    balance: "$150.00",
  },
  {
    id: "5",
    status: "Lien",
    unitType: "Storage Unit (10 x 12)",
    customer: "Maria Garcia",
    phone: "",
    cellPhone: "(903) 555-0125",
    email: "mgarcia@email.com",
    balance: "$450.00",
  },
  {
    id: "6",
    status: "Locked Out",
    unitType: "Storage Unit (10 x 8)",
    customer: "David Johnson",
    phone: "(903) 555-0126",
    cellPhone: "",
    email: "djohnson@email.com",
    balance: "$225.00",
  },
  {
    id: "7",
    status: "Reserved (Marketplace)",
    unitType: "Storage Unit (15 x 10)",
    customer: "Sarah Williams",
    phone: "(903) 555-0127",
    cellPhone: "(903) 555-0128",
    email: "swilliams@email.com",
    balance: "$0.00",
  },
  {
    id: "8",
    status: "Moving Out",
    unitType: "Storage Unit (10 x 8)",
    customer: "James Brown",
    phone: "",
    cellPhone: "(903) 555-0129",
    email: "jbrown@email.com",
    balance: "$0.00",
  },
  {
    id: "9",
    status: "Pending",
    unitType: "Storage Unit (20 x 10)",
    customer: "Emily Davis",
    phone: "(903) 555-0130",
    cellPhone: "",
    email: "edavis@email.com",
    balance: "$0.00",
  },
  {
    id: "10",
    status: "Pre-Lien",
    unitType: "Storage Unit (10 x 8)",
    customer: "Michael Wilson",
    phone: "(903) 555-0131",
    cellPhone: "(903) 555-0132",
    email: "mwilson@email.com",
    balance: "$300.00",
  },
  {
    id: "11",
    status: "Reserved",
    unitType: "Storage Unit (10 x 15)",
    customer: "Lisa Anderson",
    phone: "",
    cellPhone: "(903) 555-0133",
    email: "landerson@email.com",
    balance: "$0.00",
  },
  {
    id: "12",
    status: "Unavailable",
    unitType: "Storage Unit (10 x 8)",
    customer: "",
    phone: "",
    cellPhone: "",
    email: "",
    balance: "$0.00",
  },
  {
    id: "13",
    status: "Auction",
    unitType: "Storage Unit (10 x 12)",
    customer: "Thomas Martinez",
    phone: "(903) 555-0134",
    cellPhone: "",
    email: "tmartinez@email.com",
    balance: "$600.00",
  },
  // ... rest of the mock data (keeping it for brevity, but in real code it would all be here)
]

