import { int, sqliteTable, text, } from "drizzle-orm/sqlite-core";

export const customersTable = sqliteTable("customers", {
  id: text("id").primaryKey(),
  fullName: text("full_name").notNull(),
  address: text("address"),
  city: text("city"),
  state: text("state"),
  zip: text("zip"),
  cellPhone: text("cell_phone"),
  email: text("email").unique(),
  username: text("username").unique(),
  password: text("password"),
  disableCustomerLogin: int("disable_customer_login", { mode: "boolean" }).default(false),
  profilePicture: text("profile_picture"),
  photoId: text("photo_id"),
  dateOfBirth: text("date_of_birth"),
  driversLicenseExpiration: text("drivers_license_expiration"),
  militaryService: int("military_service", { mode: "boolean" }).default(false),
  militaryBranch: text("military_branch"),
  militaryActiveDuty: int("military_active_duty", { mode: "boolean" }).default(false),
  militaryReserveNationalGuardOrTexasStateGuard: int("military_reserve_national_guard_or_texas_state_guard", { mode: "boolean" }).default(false),
  propertyToBeStored: text("property_to_be_stored"),
  taxExempt: int("tax_exempt", { mode: "boolean" }).default(false),
  lateFeeExempt: int("late_fee_exempt", { mode: "boolean" }).default(false),
  invoiceNote: text("invoice_note"),
  notes: text("notes"),
  createdAt: text("created_at").default("CURRENT_TIMESTAMP"),
  createdBy: text("created_by"),
  updatedAt: text("updated_at").default("CURRENT_TIMESTAMP"),
  lastUpdatedBy: text("last_updated_by"),
});